name = "agent-bounties"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "6a0bf22a5ff120f19789f29eb4196ce2"

routes = [
  { pattern = "bounty.drx4.xyz", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "agent-bounties"
database_id = "6b0cc1ee-6579-4d15-938a-1262d5765d6e"

[triggers]
crons = ["*/5 * * * *"]
